/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restuarant.view;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import restuarant.controller.ConnectionBuilder;

/**
 *
 * @author taloey
 */
public class AllOrder extends javax.swing.JFrame {

    /**
     * Creates new form AllOrder
     */
    private int username = -1;
    public AllOrder(int user) {
        username = user;
        initComponents();
    }
    public AllOrder() {
        initComponents();
    }

    public void allDetail(){
        Statement s = null;
        try {
            Orderdetail.setModel(new DefaultTableModel());
            DefaultTableModel model = (DefaultTableModel) Orderdetail.getModel();
            model.addColumn("UserID");
            model.addColumn("OrderID");
            model.addColumn("Orderdate");
            model.addColumn("MenuName");
            model.addColumn("MenuPrice");
            model.addColumn("Quantity");
            model.addColumn("Total");

            Connection con = ConnectionBuilder.getConnection();
            String sql = "select o.Totalprice, From Orders o join User u on o.User_UserID = u.UserID "
                    + "join MenuDetail d on o.Order_ID = d.Orders_OrderID join Menu m on d.Menu_MenuID = m.Menu_ID ";
            s = con.createStatement();
            ResultSet rs = s.executeQuery(sql);
            int row = 0;
            while (rs != null && rs.next()) {
                model.addRow(new Object[0]);
                model.setValueAt(rs.getString("m.Menu_ID"), row, 0);
                model.setValueAt(rs.getString("m.Menu_Name"), row, 1);
                model.setValueAt(rs.getString("m.Menu_Description"), row, 2);
                model.setValueAt(rs.getString("m.Menu_Price"), row, 3);
                model.setValueAt(rs.getString("s.Status_Name"), row, 4);
                model.setValueAt(rs.getString("t.Type_Name"), row, 5);
            

                row++;
            }
            rs.close();
            con.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Orderdetail = new javax.swing.JTable();
        CheckDetail = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Orderdetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Orderdetail);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 190, 570, 490);

        CheckDetail.setText("Detail");
        getContentPane().add(CheckDetail);
        CheckDetail.setBounds(850, 220, 81, 29);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GuiImg/chi1.jpg"))); // NOI18N
        Background.setText("jLabel1");
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllOrder().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton CheckDetail;
    private javax.swing.JTable Orderdetail;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
