/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restuarant.view;

import java.util.ArrayList;
import restuarant.controller.Function;

/**
 *
 * @author ASUS
 */
public class Desserts extends javax.swing.JFrame {

    /**
     * Creates new form Desserts
     */
    private int username = -1;

    public Desserts(int user) {
        initComponents();
        username = user;
        setLocationRelativeTo(null);

        AllDrink.setModel(new javax.swing.AbstractListModel<String>() {
            ArrayList<String> strings = Function.getAllDessert();

            @Override
            public int getSize() {
                return strings.size();
            }

            @Override
            public String getElementAt(int i) {
                return strings.get(i);
            }
        });
    }

    public Desserts() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Homepage = new javax.swing.JButton();
        Mandish = new javax.swing.JButton();
        Dessert = new javax.swing.JButton();
        SignOut = new javax.swing.JButton();
        Drink = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        pic2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AllDrink = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        checkall = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(null);

        Homepage.setBackground(new java.awt.Color(0, 204, 204));
        Homepage.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Homepage.setForeground(new java.awt.Color(255, 255, 255));
        Homepage.setText("Homepage");
        Homepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomepageActionPerformed(evt);
            }
        });
        getContentPane().add(Homepage);
        Homepage.setBounds(220, 140, 120, 40);

        Mandish.setBackground(new java.awt.Color(0, 204, 204));
        Mandish.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Mandish.setForeground(new java.awt.Color(255, 255, 255));
        Mandish.setText("Maindish");
        Mandish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MandishActionPerformed(evt);
            }
        });
        getContentPane().add(Mandish);
        Mandish.setBounds(340, 140, 130, 40);

        Dessert.setBackground(new java.awt.Color(0, 204, 204));
        Dessert.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Dessert.setForeground(new java.awt.Color(255, 255, 255));
        Dessert.setText("Dessert");
        Dessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DessertActionPerformed(evt);
            }
        });
        getContentPane().add(Dessert);
        Dessert.setBounds(470, 140, 130, 40);

        SignOut.setBackground(new java.awt.Color(0, 204, 204));
        SignOut.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        SignOut.setForeground(new java.awt.Color(255, 255, 255));
        SignOut.setText("Sign-Out");
        SignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutActionPerformed(evt);
            }
        });
        getContentPane().add(SignOut);
        SignOut.setBounds(730, 140, 130, 40);

        Drink.setBackground(new java.awt.Color(0, 204, 204));
        Drink.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Drink.setForeground(new java.awt.Color(255, 255, 255));
        Drink.setText("Drinks");
        Drink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrinkActionPerformed(evt);
            }
        });
        getContentPane().add(Drink);
        Drink.setBounds(600, 140, 130, 40);

        description.setColumns(20);
        description.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        description.setLineWrap(true);
        description.setRows(5);
        description.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 0, 204)));
        description.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        description.setEnabled(false);
        jScrollPane1.setViewportView(description);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 530, 480, 160);

        pic2.setBackground(new java.awt.Color(255, 255, 255));
        pic2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 0, 204)));

        javax.swing.GroupLayout pic2Layout = new javax.swing.GroupLayout(pic2);
        pic2.setLayout(pic2Layout);
        pic2Layout.setHorizontalGroup(
            pic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );
        pic2Layout.setVerticalGroup(
            pic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        getContentPane().add(pic2);
        pic2.setBounds(60, 260, 390, 260);

        AllDrink.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 0, 204)));
        AllDrink.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AllDrink.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        AllDrink.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                AllDrinkValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(AllDrink);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(520, 260, 360, 260);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 200, 300, 50);

        checkall.setText("CheckDetail");
        checkall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkallActionPerformed(evt);
            }
        });
        getContentPane().add(checkall);
        checkall.setBounds(860, 90, 120, 30);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GuiImg/dessert1.jpg"))); // NOI18N
        getContentPane().add(BG);
        BG.setBounds(0, 10, 1080, 720);

        setBounds(0, 0, 1098, 767);
    }// </editor-fold>//GEN-END:initComponents

    private void DrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrinkActionPerformed
        Drink d = new Drink(username);
        this.setVisible(false);
        d.setVisible(true);
    }//GEN-LAST:event_DrinkActionPerformed

    private void HomepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomepageActionPerformed
        Welcomeuser user = new Welcomeuser(username);
        this.setVisible(false);
        user.setVisible(true);
    }//GEN-LAST:event_HomepageActionPerformed

    private void MandishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MandishActionPerformed
        Maindish md = new Maindish(username);
        this.setVisible(false);
        md.setVisible(true);
    }//GEN-LAST:event_MandishActionPerformed

    private void DessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DessertActionPerformed
        Desserts ds = new Desserts(username);
        this.setVisible(false);
        ds.setVisible(true);
    }//GEN-LAST:event_DessertActionPerformed

    private void SignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutActionPerformed
        username = -1;

        Welcome wel = new Welcome();
        this.setVisible(false);
        wel.setVisible(true);
    }//GEN-LAST:event_SignOutActionPerformed

    private void AllDrinkValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_AllDrinkValueChanged
//         System.out.println(AllDrink.getSelectedValue());
        String menu[] = Function.getMenu(AllDrink.getSelectedValue());
        jLabel1.setText(menu[0]);
        description.setText(menu[2]);
    }//GEN-LAST:event_AllDrinkValueChanged

    private void checkallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkallActionPerformed
            AllOrder al = new AllOrder(username);
        this.setVisible(false);
        al.setVisible(true);
    }//GEN-LAST:event_checkallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desserts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> AllDrink;
    private javax.swing.JLabel BG;
    private javax.swing.JButton Dessert;
    private javax.swing.JButton Drink;
    private javax.swing.JButton Homepage;
    private javax.swing.JButton Mandish;
    private javax.swing.JButton SignOut;
    private javax.swing.JButton checkall;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pic2;
    // End of variables declaration//GEN-END:variables
}
