/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restuarant.view;

import java.util.ArrayList;
import restuarant.controller.Function;

/**
 *
 * @author ASUS
 */
public class Maindish extends javax.swing.JFrame {
    
    /**
     * Creates new form Maindish
     */
    private String username = null;

   

    public Maindish(String user) {
        initComponents();
        username = user;
    }
    public Maindish() {
     initComponents();
     setLocationRelativeTo(null);
     
     
        Menuall.setModel(new javax.swing.AbstractListModel<String>() {
            ArrayList<String> strings = Function.getAllMaindish();

            @Override
            public int getSize() {
                return strings.size();
            }

            @Override
            public String getElementAt(int i) {
                return strings.get(i);
            }
        });

     
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Homepage = new javax.swing.JButton();
        Mandish = new javax.swing.JButton();
        Dessert = new javax.swing.JButton();
        SignOut = new javax.swing.JButton();
        Drink = new javax.swing.JButton();
        pic1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Menuall = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(null);

        Homepage.setBackground(new java.awt.Color(153, 153, 153));
        Homepage.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        Homepage.setText("Homepage");
        Homepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomepageActionPerformed(evt);
            }
        });
        getContentPane().add(Homepage);
        Homepage.setBounds(220, 120, 120, 30);

        Mandish.setBackground(new java.awt.Color(153, 153, 153));
        Mandish.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        Mandish.setText("Maindish");
        Mandish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MandishActionPerformed(evt);
            }
        });
        getContentPane().add(Mandish);
        Mandish.setBounds(340, 120, 130, 30);

        Dessert.setBackground(new java.awt.Color(153, 153, 153));
        Dessert.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        Dessert.setText("Dessert");
        Dessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DessertActionPerformed(evt);
            }
        });
        getContentPane().add(Dessert);
        Dessert.setBounds(470, 120, 130, 30);

        SignOut.setBackground(new java.awt.Color(153, 153, 153));
        SignOut.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        SignOut.setText("Sign-Out");
        SignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutActionPerformed(evt);
            }
        });
        getContentPane().add(SignOut);
        SignOut.setBounds(730, 120, 130, 30);

        Drink.setBackground(new java.awt.Color(153, 153, 153));
        Drink.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        Drink.setText("Drinks");
        Drink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrinkActionPerformed(evt);
            }
        });
        getContentPane().add(Drink);
        Drink.setBounds(600, 120, 130, 30);

        pic1.setBackground(new java.awt.Color(255, 255, 255));
        pic1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(204, 102, 0)));

        jLabel1.setText("2");

        javax.swing.GroupLayout pic1Layout = new javax.swing.GroupLayout(pic1);
        pic1.setLayout(pic1Layout);
        pic1Layout.setHorizontalGroup(
            pic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );
        pic1Layout.setVerticalGroup(
            pic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pic1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(pic1);
        pic1.setBounds(70, 230, 380, 330);

        Menuall.setBorder(new javax.swing.border.MatteBorder(null));
        Menuall.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Menuall.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Menuall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuallMouseClicked(evt);
            }
        });
        Menuall.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                MenuallValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(Menuall);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(560, 230, 380, 300);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 170, 330, 50);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 570, 500, 120);

        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GuiImg/maindish1.jpg"))); // NOI18N
        getContentPane().add(Background1);
        Background1.setBounds(0, -10, 1090, 730);

        setBounds(0, 0, 1098, 767);
    }// </editor-fold>//GEN-END:initComponents

    private void DrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrinkActionPerformed
        Drink d = new Drink();
        this.setVisible(false);
        d.setVisible(true);
    }//GEN-LAST:event_DrinkActionPerformed

    private void MenuallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuallMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuallMouseClicked

    private void MenuallValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_MenuallValueChanged
        System.out.println(Menuall.getSelectedValue());
        String menu[] = Function.getMenu(Menuall.getSelectedValue());
            jLabel2.setText(menu[0]);
            jTextArea1.setText(menu[2]);
        
    }//GEN-LAST:event_MenuallValueChanged

    private void HomepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomepageActionPerformed
        Welcomeuser user = new Welcomeuser(username);
        this.setVisible(false);
        user.setVisible(true);
    }//GEN-LAST:event_HomepageActionPerformed

    private void MandishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MandishActionPerformed
        Maindish md = new Maindish(username);
        this.setVisible(false);
        md.setVisible(true);
    }//GEN-LAST:event_MandishActionPerformed

    private void DessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DessertActionPerformed
        Desserts ds = new Desserts(username);
        this.setVisible(false);
        ds.setVisible(true);
    }//GEN-LAST:event_DessertActionPerformed

    private void SignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutActionPerformed
         username = null;
        
        Welcome wel = new Welcome();
        this.setVisible(false);
        wel.setVisible(true);
    }//GEN-LAST:event_SignOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maindish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maindish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maindish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maindish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maindish().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background1;
    private javax.swing.JButton Dessert;
    private javax.swing.JButton Drink;
    private javax.swing.JButton Homepage;
    private javax.swing.JButton Mandish;
    private javax.swing.JList<String> Menuall;
    private javax.swing.JButton SignOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pic1;
    // End of variables declaration//GEN-END:variables
}
