/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restuarant.view;

/**
 *
 * @author ASUS
 */
public class Maindish extends javax.swing.JFrame {

    /**
     * Creates new form Maindish
     */
    public Maindish() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Homepage = new javax.swing.JButton();
        Mandish = new javax.swing.JButton();
        Dessert = new javax.swing.JButton();
        SignOut = new javax.swing.JButton();
        Drink = new javax.swing.JButton();
        pic1 = new javax.swing.JPanel();
        Background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(null);

        Homepage.setBackground(new java.awt.Color(153, 153, 153));
        Homepage.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        Homepage.setForeground(new java.awt.Color(255, 255, 255));
        Homepage.setText("Homepage");
        getContentPane().add(Homepage);
        Homepage.setBounds(220, 120, 120, 30);

        Mandish.setBackground(new java.awt.Color(153, 153, 153));
        Mandish.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        Mandish.setForeground(new java.awt.Color(255, 255, 255));
        Mandish.setText("Maindish");
        getContentPane().add(Mandish);
        Mandish.setBounds(340, 120, 130, 30);

        Dessert.setBackground(new java.awt.Color(153, 153, 153));
        Dessert.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        Dessert.setForeground(new java.awt.Color(255, 255, 255));
        Dessert.setText("Dessert");
        getContentPane().add(Dessert);
        Dessert.setBounds(470, 120, 130, 30);

        SignOut.setBackground(new java.awt.Color(153, 153, 153));
        SignOut.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        SignOut.setForeground(new java.awt.Color(255, 255, 255));
        SignOut.setText("Sign-Out");
        getContentPane().add(SignOut);
        SignOut.setBounds(730, 120, 130, 30);

        Drink.setBackground(new java.awt.Color(153, 153, 153));
        Drink.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        Drink.setForeground(new java.awt.Color(255, 255, 255));
        Drink.setText("Drinks");
        Drink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrinkActionPerformed(evt);
            }
        });
        getContentPane().add(Drink);
        Drink.setBounds(600, 120, 130, 30);

        pic1.setBackground(new java.awt.Color(255, 255, 255));
        pic1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(204, 102, 0)));

        javax.swing.GroupLayout pic1Layout = new javax.swing.GroupLayout(pic1);
        pic1.setLayout(pic1Layout);
        pic1Layout.setHorizontalGroup(
            pic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );
        pic1Layout.setVerticalGroup(
            pic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        getContentPane().add(pic1);
        pic1.setBounds(300, 220, 510, 300);

        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GuiImg/maindish1.jpg"))); // NOI18N
        getContentPane().add(Background1);
        Background1.setBounds(0, -10, 1090, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DrinkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maindish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maindish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maindish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maindish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maindish().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background1;
    private javax.swing.JButton Dessert;
    private javax.swing.JButton Drink;
    private javax.swing.JButton Homepage;
    private javax.swing.JButton Mandish;
    private javax.swing.JButton SignOut;
    private javax.swing.JPanel pic1;
    // End of variables declaration//GEN-END:variables
}
