/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restuarant.view;

import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Rectangle;
import javax.swing.WindowConstants;
import java.awt.Toolkit;
import java.sql.Connection;
import restuarant.controller.ConnectionBuilder;
import restuarant.controller.Function;
/**
 *
 * @author ASUS
 */

public class Register extends javax.swing.JFrame {
static Connection con = ConnectionBuilder.getConnection();
    private String username, password, firstname, lastname, tel, email, address;
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        FirstName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        Tel = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        OK = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("spoon-and-fork-crossed_318-33017.jpg")));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("UserName :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 190, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setText("Password :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 240, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("FirstName :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 290, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 0));
        jLabel5.setText("Tel :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(400, 380, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setText("Email :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 430, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 51, 0));
        jLabel8.setText("Address :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 480, 120, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 51, 0));
        jLabel9.setText("LastName :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(340, 340, 120, 30);
        getContentPane().add(UserName);
        UserName.setBounds(490, 190, 260, 30);
        getContentPane().add(Password);
        Password.setBounds(490, 240, 260, 30);
        getContentPane().add(FirstName);
        FirstName.setBounds(490, 290, 260, 30);
        getContentPane().add(LastName);
        LastName.setBounds(490, 340, 260, 30);
        getContentPane().add(Tel);
        Tel.setBounds(490, 380, 260, 30);
        getContentPane().add(Email);
        Email.setBounds(490, 430, 260, 30);
        getContentPane().add(Address);
        Address.setBounds(490, 480, 260, 80);

        OK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        OK.setForeground(new java.awt.Color(153, 51, 0));
        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK);
        OK.setBounds(510, 600, 80, 40);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GuiImg/regis.jpg"))); // NOI18N
        Background.setMaximumSize(new java.awt.Dimension(600, 600));
        Background.setMinimumSize(new java.awt.Dimension(600, 600));
        getContentPane().add(Background);
        Background.setBounds(0, -180, 1220, 1080);

        setBounds(0, 0, 1080, 742);
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        username = UserName.getText();
        password = Password.getText();
        firstname = FirstName.getText();
        lastname = LastName.getText();
        tel = Tel.getText();
        email = Email.getText();
        address = Address.getText();
        
        Function regis = new Function();
        regis.Register(username, password, firstname, lastname, tel, email, address);

        LogInForm log = new LogInForm();
        this.setVisible(false);
        log.setVisible(true);
    }//GEN-LAST:event_OKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
               
                Register myFrame1 = new Register( );

         myFrame1.setExtendedState(MAXIMIZED_BOTH);

        myFrame1.setDefaultCloseOperation ( WindowConstants.EXIT_ON_CLOSE );
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JLabel Background;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField LastName;
    private javax.swing.JButton OK;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField Tel;
    private javax.swing.JTextField UserName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
