/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restuarant.view;

/**
 *
 * @author ASUS
 */
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Toolkit;
import javax.swing.WindowConstants;
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Welcome = new javax.swing.JLabel();
        Mainpage = new javax.swing.JButton();
        Feedbackk = new javax.swing.JButton();
        LogIn = new javax.swing.JButton();
        Regis = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Drink = new javax.swing.JButton();
        Desserts = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sum-jang Restaurant");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("spoon-and-fork-crossed_318-33017.jpg")));
        setSize(new java.awt.Dimension(1220, 1080));
        getContentPane().setLayout(null);

        Welcome.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 70)); // NOI18N
        Welcome.setForeground(new java.awt.Color(255, 255, 255));
        Welcome.setText("Welcome To Sum-jang");
        getContentPane().add(Welcome);
        Welcome.setBounds(140, 30, 850, 150);

        Mainpage.setBackground(new java.awt.Color(255, 51, 51));
        Mainpage.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        Mainpage.setForeground(new java.awt.Color(255, 255, 255));
        Mainpage.setText("Mainpage");
        Mainpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainpageActionPerformed(evt);
            }
        });
        getContentPane().add(Mainpage);
        Mainpage.setBounds(220, 240, 100, 20);

        Feedbackk.setBackground(new java.awt.Color(255, 51, 51));
        Feedbackk.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        Feedbackk.setForeground(new java.awt.Color(255, 255, 255));
        Feedbackk.setText("Feedback");
        Feedbackk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeedbackkActionPerformed(evt);
            }
        });
        getContentPane().add(Feedbackk);
        Feedbackk.setBounds(390, 240, 110, 20);

        LogIn.setBackground(new java.awt.Color(255, 51, 51));
        LogIn.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        LogIn.setForeground(new java.awt.Color(255, 255, 255));
        LogIn.setText("Log-In");
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });
        getContentPane().add(LogIn);
        LogIn.setBounds(880, 200, 70, 20);

        Regis.setBackground(new java.awt.Color(255, 51, 51));
        Regis.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        Regis.setForeground(new java.awt.Color(255, 255, 255));
        Regis.setText("Resgister");
        Regis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisActionPerformed(evt);
            }
        });
        getContentPane().add(Regis);
        Regis.setBounds(750, 200, 100, 20);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 51)));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(160, 370, 320, 290);

        Drink.setBackground(new java.awt.Color(255, 51, 51));
        Drink.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        Drink.setText("Drink");
        getContentPane().add(Drink);
        Drink.setBounds(570, 240, 97, 29);

        Desserts.setBackground(new java.awt.Color(255, 51, 51));
        Desserts.setText("Desserts");
        Desserts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DessertsActionPerformed(evt);
            }
        });
        getContentPane().add(Desserts);
        Desserts.setBounds(720, 240, 99, 29);

        background.setBackground(new java.awt.Color(255, 51, 51));
        background.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GuiImg/workWel.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, -210, 1220, 1170);

        setSize(new java.awt.Dimension(1096, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MainpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainpageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MainpageActionPerformed

    private void FeedbackkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeedbackkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FeedbackkActionPerformed

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
        LogInForm login = new LogInForm();
            this.setVisible(false);
            login.setVisible(true);
    }//GEN-LAST:event_LogInActionPerformed

    private void RegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisActionPerformed

    private void DessertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DessertsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DessertsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Welcome myFrame2 = new Welcome( );
                myFrame2.setExtendedState(MAXIMIZED_BOTH);
                myFrame2.setDefaultCloseOperation ( WindowConstants.EXIT_ON_CLOSE );
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Desserts;
    private javax.swing.JButton Drink;
    private javax.swing.JButton Feedbackk;
    private javax.swing.JButton LogIn;
    private javax.swing.JButton Mainpage;
    private javax.swing.JButton Regis;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
